#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a pytest-embedded test template.")
    parser.add_argument("--out", default="test_embedded_debug.py")
    parser.add_argument("--test-name", default="test_golden_packet_boot")
    args = parser.parse_args()
    text = f'''def {args.test_name}(dut):
    """pytest-embedded skeleton generated by embedded-debug."""
    dut.expect("READY", timeout=10)
    dut.write("debug status")
    dut.expect("PASS", timeout=10)
'''
    path = Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
