#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

try:
    import yaml  # type: ignore
except Exception:  # pragma: no cover
    yaml = None


KEYWORDS = [
    "hardfault",
    "fault",
    "panic",
    "guru meditation",
    "probe defer",
    "failed to initialize",
    "device not ready",
    "nack",
    "timeout",
    "dma",
    "cache",
    "priority inversion",
]


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract a short structured public failure case summary from raw API JSON.")
    parser.add_argument("--raw", required=True, help="Raw JSON file produced by a fetch script.")
    parser.add_argument("--out-dir", default="research/public_cases/extracted", help="Extracted output directory.")
    parser.add_argument("--case-id", help="Optional case ID. Defaults to a hash of source URL/title.")
    parser.add_argument("--platform", default="unknown", help="Platform hint for the extracted case.")
    args = parser.parse_args()

    raw_path = Path(args.raw)
    payload = json.loads(raw_path.read_text(encoding="utf-8"))
    item = first_item(payload)
    if not item:
        raise SystemExit("No item found in raw payload")

    source = source_from_item(payload, item)
    case_id = args.case_id or make_case_id(source["url"], source["title"])
    case = {
        "case_id": case_id,
        "source": source,
        "platform": args.platform,
        "symptoms": extract_symptoms(item),
        "logs": extract_log_signatures(item),
        "evidence_present": ["source URL", "title", "public metadata"],
        "evidence_missing": ["full debug packet", "toolchain version", "board revision", "verification experiment"],
        "candidate_root_causes": ["candidate only; requires human review"],
        "verification_steps": ["Create a debug packet from project artifacts before promotion."],
        "outcome": "extracted summary requires review",
        "review": {
            "review_status": "extracted",
            "promote_to_pattern": False,
            "promote_to_golden_packet": False,
            "reviewer_notes": "Generated by extract_failure_case.py; verify before promotion.",
        },
    }
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{case_id}.yaml"
    write_yaml_or_json(out_path, case)
    print(json.dumps({"ok": True, "out": str(out_path)}, sort_keys=True))


def first_item(payload: dict[str, object]) -> dict[str, object] | None:
    items = payload.get("items")
    if isinstance(items, list) and items:
        first = items[0]
        return first if isinstance(first, dict) else None
    return None


def source_from_item(payload: dict[str, object], item: dict[str, object]) -> dict[str, str]:
    url = str(item.get("url") or item.get("html_url") or item.get("link") or "")
    title = str(item.get("title") or "untitled public case")
    created = str(item.get("created_at") or item.get("createdAt") or item.get("creation_date") or "unknown")
    source_api = str(payload.get("source_api") or "unknown_api")
    return {
        "type": source_api,
        "url": url,
        "title": compact(title),
        "date": created,
        "license_or_terms_note": "Fetched via official API; retain URL and avoid copying long source text.",
    }


def extract_symptoms(item: dict[str, object]) -> list[str]:
    text = item_text(item).lower()
    hits = [keyword for keyword in KEYWORDS if keyword in text]
    if hits:
        return [f"Public source mentions: {', '.join(sorted(set(hits)))}"]
    return ["No failure keyword extracted; manual review required."]


def extract_log_signatures(item: dict[str, object]) -> list[str]:
    text = item_text(item)
    signatures = []
    for pattern in [r"error\s+0x[0-9a-fA-F]+", r"-EPROBE_DEFER", r"LoadProhibited", r"NACK", r"timeout"]:
        if re.search(pattern, text):
            signatures.append(pattern)
    return signatures[:5]


def item_text(item: dict[str, object]) -> str:
    parts = [str(item.get(name, "")) for name in ("title", "body", "excerpt")]
    return "\n".join(parts)


def compact(text: str, limit: int = 180) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def make_case_id(url: str, title: str) -> str:
    base = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")[:48] or "public_case"
    digest = hashlib.sha1((url + title).encode("utf-8")).hexdigest()[:8]
    return f"{base}_{digest}"


def write_yaml_or_json(path: Path, data: dict[str, object]) -> None:
    if yaml is not None:
        path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=False), encoding="utf-8")
    else:
        path.with_suffix(".json").write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")


if __name__ == "__main__":
    main()
